services:
  execution-base:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    ports:
      - "8545:8545"       # RPC
      - "8546:8546"       # websocket
      - "7301:6060"       # metrics
      - "30303:30303"     # P2P TCP
      - "30303:30303/udp" # P2P UDP
    command: [ "bash", "./execution-entrypoint" ]
    volumes:
        - ${HOST_DATA_DIR}:/data
    env_file:
     - .env.mainnet
    networks:
      - eth-docker_default
  node-base:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    depends_on:
      - execution-base
    ports:
      - "7545:8545"     # RPC
      - "9222:9222"     # P2P TCP
      - "9222:9222/udp" # P2P UDP 
      - "7300:7300"     # metrics
      - "6060:6060"     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    env_file:
     - .env.mainnet
    networks:
      - eth-docker_default

networks:
  eth-docker_default:
    external: true
